### ISSUE TITLE
Misparsing of speaker names

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/PolyglotDB#120]
I've discovered with SOTC that speaker names are not being fully parsed, which means that tokens from different files are being parsed as the same speaker. For example, filenames that start with `00-M` are being grouped as the same speaker (though they should all be parsed as separate speakers): 

```
  node_Discourse_name node_Speaker_name
1       00-M-f05-medi              00-M
2       00-M-f04-medi              00-M
3       00-M-f04-medi              00-M
4       00-M-m03-medi              00-M
5       00-M-f05-medi              00-M
6       00-M-f02-medi              00-M
```

Found this using `autovot.py`, where the query is written as

```
            #Get a query of necessary info
            q = g.query_graph(g.phone).filter(g.phone.subset == "stops").columns(g.phone.label, \
                    g.phone.begin, g.phone.end, g.phone.vot.confidence, \
                    g.phone.vot.begin, g.phone.vot.end, g.phone.word.label, \
                    g.phone.following.label, g.phone.syllable.stress, \
                    g.phone.syllable.label, g.phone.utterance.speech_rate, \
                    g.phone.word.begin, g.phone.word.end, \
                    g.phone.discourse.name, g.phone.speaker.name).order_by(g.phone.begin)
```

**Comment by msonderegger** [comment]
@james-tanner nice catch!  This actually looks like something a mortal could fix (e.g. you if you have time) and submit a pull request for.   In the parsers:

https://github.com/MontrealCorpusTools/PolyglotDB/tree/master/polyglotdb/io/parsers

you can see in Aligner.py, which the labbcat parser is using (labbcat.py), that dashes in speaker names are being dealt with in a particular special way which doesn't apply for SOTC.

It looks like    `_is_valid(self, tg)` would need to be redefined in the `labbcat.py` parser which is an instance of the class in `aligner.py` .

**Comment by james-tanner** [comment]
Is that where the problem is? That function only splits names where there is a dash with spaces (` - `), which is not the SOTC format.
I think the problem is involved in the different formats for grids with vs without multiple speakers. PGDB parses it correctly when there **are** multiple speakers, because the format makes sense (i.e., `segments - XX-X-XXX'. When there is only one speaker, the transcript and segment tiers don't actually have the speaker name on them (and are just `transcript`, for example). This should be fine though, because the check for multiple speakers doesn't apply the stripping when `multiple_speakers` is False.
What would be the problem, then?

**Comment by msonderegger** [comment]
@mmcauliffe can you give James some guidance on how to proceed, or fix yourself? This turns out to be fairly high-priority.

**Comment by mmcauliffe** [comment]
Ok, take a look at: https://polyglotdb.readthedocs.io/en/latest/io.html#speaker-parsers.  Labb-Cat format, like the other aligner parsers defaults to using directory names, so I don't think there's a bug on PolyglotDB's part.  Do you set `parser.speaker_parser` anywhere in the script?

**Comment by james-tanner** [comment]
No. I'm not sure I follow - in what script would this be declared? Inside the `labbcat.parser` or somewhere else?

**Comment by mmcauliffe** [comment]
No, in the script, once `inspect_labbcat` is called, there will be a `parser` returned that should be of type `DirectorySpeakerParser`.  If it's a `FilenameSpeakerParser`, then you'll see the behavior above, otherwise it'll use the directory name as the speaker name.

**Comment by james-tanner** [comment]
I'm confused. Shouldn't Filename give you the desired behaviour? The goal is to have speakers be parsed by their filenames and not directory?
Which script? It calls functions from `common.py`, which is where `inspect_labbcat` is being called (inside `loading`). Which script should be declaring this?

**Comment by mmcauliffe** [comment]
It depends on the structure of the corpus, in general I like to have files organized into speaker directories, and I think that's how labbcat is, but maybe it's been reorganized.  If you want it based off of filename with more characters, specify it via a new filename parser like (in https://github.com/MontrealCorpusTools/SPADE/blob/master/Common/common.py#L119):

```
elif textgrid_format == "labbcat":
    from polyglotdb.io.parsers.speaker import FilenameSpeakerParser
    parser = pgio.inspect_labbcat(corpus_dir)
    parser.speaker_parser = FilenameParser(8) # 8 characters should get the unique speaker IDs
```

But regardless, are you sure that the format in the yaml is `labbcat`?  Again, everything looks correct for labbcat to use directories to parse speaker information, so filenames shouldn't enter into it at all.

**Comment by james-tanner** [comment]
So SOTC shouldn't be using directories for parsing speaker names, since multiple speakers share the same directory, and the directory name is a shared prefix. For example:
```
70-O/70-O-f01.TextGrid
70-O/70-O-f02.TextGrid
70-M/70-M-f01.TextGrid
70-M/70-M-f02.TextGrid
...
```

Where each file refers to a unique speaker. It seems to be that filename should be used to parse the speaker names.

Is there a way to not have to specify a length of characters, and instead stop at e.g., `.TextGrid`? Some of the filenames are `dd-X-Xdd`, whilst others are `dd-xxx-X-Xdd` (where d and X stand for digits and letters respectively).

**Comment by mmcauliffe** [comment]
I don't think the letter code at the end is a speaker differentiation code, but if you want it all, you can specify it as something really long like 50 characters and it'll get everything (the extension is always ignored).

**Comment by msonderegger** [comment]
@mmcauliffe yes, the code at the end does differentiate speakers.  `70-0-f01` and `70-O-f02` are different speakers.  `70-O` is a group of speakers (recorded at the same time and of similar ages).  It's not an ideal directory structure but so it goes.  I don't know how this relates to "labbcat format" but for this corpus at least James is right.

could you guys communicate e.g. on Slack to fix this? It's a blocking issue for generating data for both Jane and Glasgow ppl.  one possibility would just be to reformat the corpus so that each directory does correspond to one speaker.

**Comment by mmcauliffe** [comment]
Those aren't the codes that I'm referring to, `70-0-f01` is the speaker ID, but some of them have `-medi` or `-labo` at the end, which I think correspond to other information not related to the speaker.

Regardless, I'm going to close this here because it's not a PolyglotDB issue, it's a dataset organization/SPADE script issue.

**Comment by msonderegger** [comment]
yikes sorry, got it.
