### ISSUE TITLE
CSV enrichment files don't escape column names

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/PolyglotDB#128]
Having `.` in column names (ala R column naming schemes) causes enrichment to crash because the column names are not escaped.  Periods in names might just be unusable, since python won't like direct reference (i.e., `c.phone.speaker.birth.place` will get interpreted differently than `c.phone.speaker.birth_place`).  At the very least there should be a clear error to not use periods in column names.

**Comment by msonderegger** [comment]
yes, that sounds like a reasonable restriction.
