### ISSUE TITLE
FAVE-like formant track enrichment

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/PolyglotDB#133]
Currently there is functionality for getting point measurements based on a FAVE-like algorithm, but no functionality for generating dynamic tracks using a similar algorithm.

So currently the basic version of the FAVE algorithm for point measures returns X number of point measures for various N formants, and then selects the point measures that are close to prototypical values for formants.  The dynamic tracks version would be similar to this, saving a single track per vowel where a particular part of the track (33%) is closest to a the prototype.

I think the easiest route to implement is to use a praat script that returns a track for each value of N formants, rather than returning points per N formants.  Some dev for Pyraat might be necessary to allow this.  And then for each given track, get the value at the 33% point (linear interpolation between two points in the track might be necessary), and do the same calculation that's currently done for refined formant points.

So basic steps:

- [ ] Create new praat script based on https://github.com/MontrealCorpusTools/PolyglotDB/blob/master/polyglotdb/acoustics/formants/multiple_num_formants.praat that returns tracks like https://github.com/mmcauliffe/Conch-sounds/blob/master/conch/analysis/formants/formant_track_segment.praat
- [ ] Create new python function for refined_tracks similar to https://github.com/MontrealCorpusTools/PolyglotDB/blob/master/polyglotdb/acoustics/formants/refined.py#L42 for using prototypes to select tracks, and save them like in https://github.com/MontrealCorpusTools/PolyglotDB/blob/master/polyglotdb/acoustics/formants/base.py#L51

**Comment by msonderegger** [comment]
as discussed on Slack / to remind myself -- this will require changes both on Polyglot side and in Praat script used to generate formant tracks

**Comment by MichaelGoodale** [comment]
@mmcauliffe  So I've been taking a look at the praat scripts for a bit now and I think I've got my head around how they work. For the new script for FAVE-style tracks, should that include all this stuff about moving up a half-window or whatever *per track* or *per point on the track*. Just not sure if I should do it once and then use those parametres across the whole track or change the measurement for each point. My assumption is *per track* but let me know if you'd rather I do it per each point

**Comment by mmcauliffe** [comment]
Yeah, so it'd be per track.  So find the optimal number of formants based on comparing the formant values and bandwidths at the 33% point to the prototype formants and bandwidths for the vowel, and then saving the track that was generated using that value of n_formants.
