### ISSUE TITLE
Gender not included in refined formants

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/PolyglotDB#141]
Currently the [paper](https://spade.glasgow.ac.uk/wp-content/uploads/2019/04/icphs2019-SPADE-vowels_revision.pdf) for the refined formants references a different max frequency for LPCs depending on gender, but the actual function in PolyglotDB does not seem to change the frequency based on gender. @jeffmielke Is this just a mistake with the paper or should the refined formant function also change frequency based on gender.

**Comment by jeffmielke** [comment]
It's not something I implemented. I took for granted that it was already
being done and it's possible that it wasn't and I didn't notice. I would
ask Morgan about this because he knows more about the making of the first
version of the formant measurement scheme.

Jeff

**Comment by jeffmielke** [comment]
It looks generate_base_formants_function() in helper.py is considering
gender and setting the max frequency, but
generate_variable_formants_point_function() is the one that's being used in
refined.py. Maybe that was an oversight or maybe someone had a reason for
doing it that way. A potential issue is that it is checking whether gender
is 'M', but not all corpora indicate gender with M or F, for example SCOTS
uses Male/Female.

Jeff

Jeff Mielke
Associate professor
Linguistics program
Department of English
North Carolina State University

**Comment by MichaelGoodale** [comment]
I think @mmcauliffe had said that he doesn't think the gender frequency will make a significant difference since if it's always on the higher side, men will have just another LPC coefficient or something along those lines, but switching the frequency will cause a big slow down in speed.

**Comment by jeffmielke** [comment]
That should be fine. Erik Thomas said that he doesn't usually change the
max frequency when he's measuring formants manually, because changing the
number of coefficients is sufficient.

It's hard for me to see how measuring some tokens with 5000 and some with
5500 would affect speed, but it seems like it's fine to leave it the way it
is for the sake of simplicity.

Jeff

Jeff Mielke
Associate professor
Linguistics program
Department of English
North Carolina State University

**Comment by msonderegger** [comment]
Sorry for delay, both.  It sounds good to just leave the algorithm the way it is.

@jeffmielke I think @mmcauliffe 's logic was that under the hood Praat resamples the waveform before formant measurement for each new frequency cutoff, and iterated over many (many) waveforms there would be a performance hit.  I'm not sure if he checked or if I'm reporting accurately.
