### ISSUE TITLE
Tutorial corpus missing

### ISSUE THREAD

**Issue by korakot** [MontrealCorpusTools/PolyglotDB#162]
From the documentation page here

https://polyglotdb.readthedocs.io/en/latest/tutorial_first_steps.html

The link to download corpus in dropbox is deleted.

https://www.dropbox.com/s/o3fdzem4soh4mtf/pg_tutorial.zip?dl=0

Could you update it to the new link?

**Comment by michaelhaaf** [comment]
This will be addressed in https://github.com/MontrealCorpusTools/PolyglotDB/pull/168
