### ISSUE TITLE
Tutorial corpus link broken

### ISSUE THREAD

**Issue by lxy2304** [MontrealCorpusTools/PolyglotDB#187]
File Not Found at 
https://mcgill-my.sharepoint.com/:f:/g/personal/michael_haaf_mcgill_ca/EjTbG6TDJOFFgAWSD6Hq1FABeakjZRkFL33z4F1DuPDcMw?e=1zQhw3

**Comment by msonderegger** [comment]
Thanks @lxy2304 -- I'm going to communicate about this on Slack because it involves files on our local servers.
