### ISSUE TITLE
Update setup.py with modern practice for improved compatibility

### ISSUE THREAD

**Issue by lxy2304** [MontrealCorpusTools/PolyglotDB#189]
1. pgdb executable script on Windows:
  Issue: The script is not generated correctly.
  Proposed Fix: Update setup.py to use entry_points = {'console_scripts': []} instead of scripts = [] for better cross-platform compatibility. This requires rewriting bin/pgdb as a function and relocating it to the polyglotdb directory.

2. Specify scipy version:
     Requirement: conch-sounds uses scipy < 1.13. Recent changes in scipy~=1.13 caused ImportError: cannot import name 'gaussian' from 'scipy.signal'.
    Proposed Fix: Specify scipy version ~= 1.12.0
 
3. python setup.py install / setup.py install:
    Issue: This approach to install package from source code is outdated. 
   Proposed Fix: May consider updating to a more modern practice with pyproject.toml and 'pip install .' 

4. setuptools.command.test:
  Issue: This test command provided by setuptools is deprecated.
   Proposed Fix: Remove the test command from setup.py

**Comment by msonderegger** [comment]
Hello @lxy2304 -- I checked in with @mmcauliffe about this. All changes above sound good.  Specifically:

1. You could look at the code for Montreal Forced Aligner (his project which is more actively maintained) to see how CLI is implemented there, as a working model.
2. Conch issue: short-term, sounds good to specify scipy version ~= 1.12.0, longer-term, he'll need to fix conch.  He says you could just try to fix the issue yourself and make a pull request with the changes.
3. This makes sense.  Again, you could see MFA for a working example using pyproject.toml
4. Sounds good. (instead you use pytest)

So you can go ahead and implement.  Just comment here if there's anything else you were wondering about.
