### ISSUE TITLE
Import BAS Partitur format

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/PolyglotDB#52]
- [ ] Inspect function for Partitur
- [ ] Parser class for Partitur

The inspect function should return a PartiturParser for a given file, that loads (a subset of) the tiers in the file into tier objects that PolyglotDB can use

**Comment by msonderegger** [comment]
Assign this to Elias (but without a date at this point)?

(And, should I be writing this kind of comment here?)

**Comment by mmcauliffe** [comment]
Yeah, I was just putting this here since it's more of a GitHub type thing than a Basecamp type thing.

**Comment by msonderegger** [comment]
got it.
